version = "1.0"
robust = "normal"

[models]
wpl = "./models/wpl"
oml = "./models/oml"
knowledge = "./models/knowledge"

[topology]
sources = "./topology/sources"
sinks = "./topology/sinks"

[performance]
rate_limit_rps = 20000
parse_workers = 4

[log_conf]
level = "warn,ctrl=info,data=error"
output = "File"
[log_conf.file]
path = "./data/logs/"

[[stat.pick]]
key = "pick_stat"
target = "*"
[[stat.parse]]
key = "parse_stat"
target = "*"
[[stat.sink]]
key = "sink_stat"
target = "*"

[admin_api]
enabled = false
bind = "127.0.0.1:19090"
[admin_api.tls]
enabled = false
[admin_api.auth]
mode = "bearer_token"
token_file = "${HOME}/.warp_parse/admin_api.token"
