use std::fs;
use std::path::Path;

// Embedded template files generated by build.rs from docker/default_setting/
include!(concat!(env!("OUT_DIR"), "/template.rs"));

// =====================================================================
// Mode filtering
// =====================================================================

fn scope_matches(template_path: &str, scope: &str) -> bool {
    match scope {
        "full" | "normal" => true,
        "rules" => {
            template_path.starts_with("models/rules/")
                || template_path.starts_with("models/schemas/")
                || template_path.starts_with("models/scenarios/")
                || template_path == "conf/wfusion.toml"
                || template_path.starts_with("connectors/")
                || template_path == "run.sh"
                || template_path == "smoke.sh"
        }
        "conf" => {
            template_path.starts_with("conf/")
                || template_path.starts_with("topology/sinks/")
                || template_path.starts_with("topology/sources/")
                || template_path.starts_with("connectors/")
                || template_path == "run.sh"
                || template_path == "smoke.sh"
        }
        _ => true,
    }
}

// =====================================================================
// Path mapping (docker template → wf-rules project)
// =====================================================================

fn map_path(template_path: &str) -> String {
    let pairs: &[(&str, &str)] = &[
        ("models/rules/", "rules/"),
        ("models/schemas/", "schemas/"),
        ("models/scenarios/", "scenarios/"),
        ("topology/sinks/", "sinks/"),
        ("topology/sources/", "sources/"),
    ];
    for (prefix, replacement) in pairs {
        if let Some(rest) = template_path.strip_prefix(prefix) {
            return format!("{replacement}{rest}");
        }
    }
    template_path.to_string()
}

// =====================================================================
// Init
// =====================================================================

pub fn init_project(project_dir: &str, _name: &str, scope: &str) -> Result<(), String> {
    let root = Path::new(project_dir);

    if root.exists()
        && root
            .read_dir()
            .ok()
            .map(|mut d| d.next().is_some())
            .unwrap_or(false)
    {
        return Err(format!(
            "directory '{}' already exists and is not empty",
            root.display()
        ));
    }

    fs::create_dir_all(root).map_err(|e| format!("create project dir: {e}"))?;

    for (template_path, data) in TEMPLATE_FILES {
        if !scope_matches(template_path, scope) {
            continue;
        }
        let mapped = map_path(template_path);
        let full = root.join(&mapped);

        if let Some(parent) = full.parent() {
            fs::create_dir_all(parent).map_err(|e| format!("create parent for {mapped}: {e}"))?;
        }
        fs::write(&full, data).map_err(|e| format!("write {mapped}: {e}"))?;
    }

    // Make scripts executable (on Unix)
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        for script in &["run.sh", "smoke.sh"] {
            let path = root.join(script);
            if path.exists() {
                let mut perms = fs::metadata(&path)
                    .map_err(|e| format!("metadata {script}: {e}"))?
                    .permissions();
                perms.set_mode(0o755);
                fs::set_permissions(&path, perms).map_err(|e| format!("chmod {script}: {e}"))?;
            }
        }
    }

    println!(
        "✓ wf-rules project created at {} (scope: {scope})",
        root.canonicalize().unwrap_or(root.to_path_buf()).display()
    );
    println!("  cd {} && wfusion run", project_dir);
    Ok(())
}

// =====================================================================
// Remote bootstrap (stub)
// =====================================================================

pub fn init_from_remote(
    project_dir: &str,
    repo_url: &str,
    version: Option<&str>,
) -> Result<(), String> {
    let _ = (project_dir, repo_url, version);
    Err("remote bootstrap not yet implemented (TODO)".to_string())
}
