use std::fs;
use std::path::Path;

// Embedded template files generated by build.rs from docker/default_setting/
include!(concat!(env!("OUT_DIR"), "/template.rs"));

// =====================================================================
// Mode filtering
// =====================================================================

fn scope_matches(template_path: &str, scope: &str) -> bool {
    match scope {
        "full" | "normal" => true,
        "rules" => {
            template_path.starts_with("models/rules/")
                || template_path.starts_with("models/schemas/")
                || template_path.starts_with("models/scenarios/")
                || template_path == "conf/wfusion.toml"
                || template_path.starts_with("connectors/")
                || template_path == "run.sh"
                || template_path == "smoke.sh"
        }
        "conf" => {
            template_path.starts_with("conf/")
                || template_path.starts_with("topology/sinks/")
                || template_path.starts_with("topology/sources/")
                || template_path.starts_with("connectors/")
                || template_path == "run.sh"
                || template_path == "smoke.sh"
        }
        _ => true,
    }
}

// =====================================================================
// Init
// =====================================================================

pub fn init_project(project_dir: &str, _name: &str, scope: &str) -> Result<(), String> {
    let root = Path::new(project_dir);

    if root.exists()
        && root
            .read_dir()
            .ok()
            .map(|mut d| d.next().is_some())
            .unwrap_or(false)
    {
        return Err(format!(
            "directory '{}' already exists and is not empty",
            root.display()
        ));
    }

    fs::create_dir_all(root).map_err(|e| format!("create project dir: {e}"))?;

    for (template_path, data) in TEMPLATE_FILES {
        if !scope_matches(template_path, scope) {
            continue;
        }
        let full = root.join(template_path);

        if let Some(parent) = full.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("create parent for {template_path}: {e}"))?;
        }
        fs::write(&full, data).map_err(|e| format!("write {template_path}: {e}"))?;
    }

    // Make scripts executable (on Unix)
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        for script in &["run.sh", "smoke.sh"] {
            let path = root.join(script);
            if path.exists() {
                let mut perms = fs::metadata(&path)
                    .map_err(|e| format!("metadata {script}: {e}"))?
                    .permissions();
                perms.set_mode(0o755);
                fs::set_permissions(&path, perms).map_err(|e| format!("chmod {script}: {e}"))?;
            }
        }
    }

    println!(
        "✓ wf-rules project created at {} (scope: {scope})",
        root.canonicalize().unwrap_or(root.to_path_buf()).display()
    );
    println!("  cd {} && wfusion run", project_dir);
    Ok(())
}

// =====================================================================
// Remote bootstrap (stub)
// =====================================================================

pub fn init_from_remote(
    project_dir: &str,
    repo_url: &str,
    version: Option<&str>,
) -> Result<(), String> {
    let _ = (project_dir, repo_url, version);
    Err("remote bootstrap not yet implemented (TODO)".to_string())
}
