use std::fs;
use std::path::Path;

// Embedded template files generated by build.rs from docker/default_setting/
include!(concat!(env!("OUT_DIR"), "/template.rs"));

/// Map template paths to project paths.
/// The docker/default_setting/ layout uses different directory names
/// than a wf-rules project. This function remaps them.
fn map_path(template_path: &str) -> String {
    let pairs: &[(&str, &str)] = &[
        ("models/rules/", "rules/"),
        ("models/schemas/", "schemas/"),
        ("models/scenarios/", "scenarios/"),
        ("topology/sinks/", "sinks/"),
        ("topology/sources/", "sources/"),
    ];

    for (prefix, replacement) in pairs {
        if let Some(rest) = template_path.strip_prefix(prefix) {
            return format!("{replacement}{rest}");
        }
    }
    template_path.to_string()
}

pub fn init_project(project_dir: &str, _name: &str) -> Result<(), String> {
    let root = Path::new(project_dir);

    if root.exists()
        && root
            .read_dir()
            .ok()
            .map(|mut d| d.next().is_some())
            .unwrap_or(false)
    {
        return Err(format!(
            "directory '{}' already exists and is not empty",
            root.display()
        ));
    }

    fs::create_dir_all(root).map_err(|e| format!("create project dir: {e}"))?;

    for (template_path, data) in TEMPLATE_FILES {
        let mapped = map_path(template_path);
        let full = root.join(&mapped);

        if let Some(parent) = full.parent() {
            fs::create_dir_all(parent).map_err(|e| format!("create parent for {mapped}: {e}"))?;
        }
        fs::write(&full, data).map_err(|e| format!("write {mapped}: {e}"))?;
    }

    // Make scripts executable (on Unix)
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        for script in &["run.sh", "smoke.sh"] {
            let path = root.join(script);
            if path.exists() {
                let mut perms = fs::metadata(&path)
                    .map_err(|e| format!("metadata {script}: {e}"))?
                    .permissions();
                perms.set_mode(0o755);
                fs::set_permissions(&path, perms).map_err(|e| format!("chmod {script}: {e}"))?;
            }
        }
    }

    println!(
        "✓ wf-rules project created at {}",
        root.canonicalize().unwrap_or(root.to_path_buf()).display()
    );
    println!("  cd {} && wfusion run", project_dir);
    Ok(())
}
