use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("template.rs");

    let template_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docker/default_setting");

    let mut files = Vec::new();
    collect_files(&template_root, &template_root, &mut files);

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs — do not edit\n");
    out.push_str("pub const TEMPLATE_FILES: &[(&str, &[u8])] = &[\n");

    for (rel_path, abs_path) in &files {
        let data = fs::read(abs_path).unwrap_or_default();
        let rel = rel_path.replace('\\', "/");
        out.push_str(&format!("    ({:?}, &{:?}),\n", rel, data.as_slice()));
    }

    out.push_str("];\n");

    fs::write(&dest, out).unwrap();
}

fn collect_files(root: &Path, dir: &Path, files: &mut Vec<(String, std::path::PathBuf)>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_files(root, &path, files);
            } else {
                let rel = path.strip_prefix(root).unwrap_or(&path);
                files.push((rel.to_string_lossy().to_string(), path));
            }
        }
    }
}
