connect = "kafka_src"
enable = true
key = "kafka_nginx"
stream_tag = "nginx_access"
brokers = "localhost:9092"
topic = "wp_nginx_logs"
group_id = "wfusion_default"
config = "auto.offset.reset=earliest"
data_format = "ndjson"
