
sources_dir = "topology/sources"
sinks = "topology/sinks"

[runtime]
executor_parallelism = 4
rule_exec_timeout = "30s"
schemas = "../../models/schemas/*.wfs"
rules = "../../models/wfl/*.wfl"

windows = "../../models/windows.toml"

[logging]
level = "debug"
format = "plain"
