version = "1.0"
[sink_group]
name = "traffic_out"
windows = ["traffic_alerts"]
[[sink_group.sinks]]
connect = "file_json_sink"
name = "traffic_json"
[sink_group.sinks.params]
base = "../data/alerts"
file = "traffic.ndjson"
