use super::*;
use crate::oracle::run_oracle;

#[test]
fn test_inject_hit_cluster_correctness() {
    let input = r#"
#[duration=10s]
scenario inject_hit<seed=42> {
    traffic {
        stream LoginWindow gen 100/s
    }
    injection {
        hit<50%> LoginWindow {
            src_ip seq {
                use(action="failed") with(5)
            }
        }
    }
    expect {
        hit(auth_fail_rule) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_auth_fail_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    assert_eq!(result.events.len(), 1000);

    // Hit clusters: 1000 * 50% = 500 events / 5 per cluster = 100 clusters
    // Count events that are inject hit events by checking src_ip pattern
    let hit_events: Vec<_> = result
        .events
        .iter()
        .filter(|e| {
            e.fields
                .get("src_ip")
                .and_then(|v| v.as_str())
                .map(|s| s.starts_with("10."))
                .unwrap_or(false)
                && e.fields
                    .get("src_ip")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .len()
                    <= 15 // typical inject IP pattern
        })
        .collect();

    // At minimum we should have some hit events
    assert!(
        hit_events.len() >= 100,
        "expected at least 100 hit events, got {}",
        hit_events.len()
    );

    // All events should be sorted by timestamp
    for w in result.events.windows(2) {
        assert!(w[0].timestamp <= w[1].timestamp);
    }
}

#[test]
fn test_inject_filter_constraint_applied() {
    // Rule has filter: success == false
    // Generated inject events must have success = false
    let input = r#"
#[duration=5s]
scenario inject_filter<seed=42> {
    traffic {
        stream LoginWindow gen 100/s
    }
    injection {
        hit<30%> LoginWindow {
            src_ip seq {
                use(success=false) with(5)
            }
        }
    }
    expect {
        hit(auth_fail_rule) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_auth_fail_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    assert_eq!(result.events.len(), 500);

    // Inject events are identified by src_ip pattern "10.x.x.x" (generated by generate_key_values)
    // Background events have different IPs from the ipv4() generator
    // Count inject events (those with src_ip starting with "10." and having typical inject pattern)
    let inject_events: Vec<_> = result
        .events
        .iter()
        .filter(|e| {
            e.fields
                .get("src_ip")
                .and_then(|v| v.as_str())
                .map(|s| s.starts_with("10.") && s.len() <= 15)
                .unwrap_or(false)
        })
        .collect();

    // Debug: print first 10 inject events
    for (i, event) in inject_events.iter().take(10).enumerate() {
        eprintln!(
            "Inject event {}: src_ip={:?}, success={:?}",
            i,
            event.fields.get("src_ip"),
            event.fields.get("success")
        );
    }

    // All inject events should have success = false due to filter
    for (i, event) in inject_events.iter().enumerate() {
        let success = event.fields.get("success").and_then(|v| v.as_bool());
        assert_eq!(
            success,
            Some(false),
            "inject event {} should have success=false due to filter, got {:?}",
            i,
            success
        );
    }

    // Run oracle — should produce alerts because inject events match filter and threshold
    let start = "2024-01-01T00:00:00Z".parse().unwrap();
    let duration = Duration::from_secs(3600);
    let oracle = run_oracle(&result.events, &plans, &start, &duration, None).unwrap();

    // We expect alerts since hit events have the correct filter value
    assert!(
        !oracle.alerts.is_empty(),
        "expected alerts from hit events with filter, got {}",
        oracle.alerts.len()
    );
}

#[test]
fn test_inject_use_predicate_conflicting_with_filter_fails() {
    let input = r#"
#[duration=5s]
scenario inject_filter_conflict<seed=42> {
    traffic {
        stream LoginWindow gen 100/s
    }
    injection {
        hit<30%> LoginWindow {
            src_ip seq {
                use(success=true) with(5)
            }
        }
    }
    expect {
        hit(auth_fail_rule) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_auth_fail_plan()];

    let err = match generate(&wfg, &schemas, &plans) {
        Ok(_) => panic!("generation should fail when use predicates conflict with rule filters"),
        Err(err) => err,
    };
    let rendered = err.report().render().to_string();
    assert!(
        rendered.contains("conflicts with rule step filter"),
        "unexpected error: {rendered}"
    );
}

#[test]
fn test_inject_near_miss_use_predicate_conflicting_with_filter_fails() {
    let input = r#"
#[duration=5s]
scenario inject_filter_conflict_nm<seed=42> {
    traffic {
        stream LoginWindow gen 100/s
    }
    injection {
        near_miss<30%> LoginWindow {
            src_ip seq {
                use(success=true) with(5)
            }
        }
    }
    expect {
        hit(auth_fail_rule) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_auth_fail_plan()];

    let err = match generate(&wfg, &schemas, &plans) {
        Ok(_) => panic!("generation should fail when use predicates conflict with rule filters"),
        Err(err) => err,
    };
    let rendered = err.report().render().to_string();
    assert!(
        rendered.contains("conflicts with rule step filter"),
        "unexpected error: {rendered}"
    );
}

#[test]
fn test_inject_use_predicates_are_step_scoped_and_typed() {
    let input = r#"
#[duration=5s]
scenario inject_step_scope<seed=42> {
    traffic {
        stream LoginWindow gen 40/s
    }
    injection {
        hit<40%> LoginWindow {
            src_ip seq {
                use(success=false) with(1)
                then use(success=true) with(1)
            }
        }
    }
    expect {
        hit(bool_chain) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_bool_chain_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    assert_eq!(result.events.len(), 200);

    let mut by_entity: std::collections::HashMap<
        String,
        Vec<(chrono::DateTime<chrono::Utc>, bool)>,
    > = std::collections::HashMap::new();
    for event in &result.events {
        let Some(entity) = event.fields.get("username").and_then(|v| v.as_str()) else {
            continue;
        };
        if !entity.starts_with("hit_username_") {
            continue;
        }
        let Some(success) = event.fields.get("success").and_then(|v| v.as_bool()) else {
            panic!(
                "inject event should keep bool type for success, got {:?}",
                event.fields.get("success")
            );
        };
        by_entity
            .entry(entity.to_string())
            .or_default()
            .push((event.timestamp, success));
    }

    assert!(
        !by_entity.is_empty(),
        "expected inject entities with generated username prefix"
    );

    for (entity, seq) in &mut by_entity {
        seq.sort_by_key(|(ts, _)| *ts);
        assert!(
            seq.len() >= 2,
            "entity {} should have at least 2 injected events, got {}",
            entity,
            seq.len()
        );
        assert!(
            !seq[0].1,
            "entity {} first step should be success=false, got {:?}",
            entity, seq[0].1
        );
        assert!(
            seq[1].1,
            "entity {} second step should be success=true, got {:?}",
            entity, seq[1].1
        );
    }
}

#[test]
fn test_syntax_extra_use_step_fails_when_rule_has_no_matching_step() {
    let input = r#"
#[duration=5s]
scenario inject_extra_use<seed=42> {
    traffic {
        stream LoginWindow gen 20/s
    }
    injection {
        hit<50%> LoginWindow {
            src_ip seq {
                use(success=false) with(5)
                use(success=true) with(1)
            }
        }
    }
    expect {
        hit(auth_fail_rule) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_auth_fail_plan()];

    let err = match generate(&wfg, &schemas, &plans) {
        Ok(_) => panic!("generation should fail when use(...) count exceeds rule steps"),
        Err(err) => err,
    };
    let rendered = err.report().render().to_string();
    assert!(
        rendered.contains("exceeds rule step count"),
        "unexpected error: {rendered}"
    );
}

#[test]
fn test_syntax_distinct_close_rejects_multiple_use_steps_for_one_rule_step() {
    let input = r#"
#[duration=10m]
scenario inject_distinct_close<seed=42> {
    traffic {
        stream LoginWindow gen 20/s
    }
    injection {
        hit<25%> LoginWindow {
            src_ip seq {
                use(success=false, dport=80) with(1)
                use(success=false, dport=443) with(1)
                use(success=false, dport=8080) with(1)
            }
        }
    }
    expect {
        hit(distinct_close) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_distinct_close_plan()];

    let err = match generate(&wfg, &schemas, &plans) {
        Ok(_) => panic!("generation should fail when use(...) count exceeds rule steps"),
        Err(err) => err,
    };
    let rendered = err.report().render().to_string();
    assert!(
        rendered.contains("exceeds rule step count"),
        "unexpected error: {rendered}"
    );
}

#[test]
fn test_syntax_use_steps_match_multi_step_bind_filters() {
    let input = r#"
#[duration=10m]
scenario inject_chain_attack<seed=42> {
    traffic {
        stream LoginWindow gen 20/s
    }
    injection {
        hit<25%> LoginWindow {
            src_ip seq {
                use(success=false, dport=80) with(5)
                use(success=true, dport=22) with(3)
            }
        }
    }
    expect {
        hit(chain_attack) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_chain_attack_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();

    let mut counts_by_entity: std::collections::HashMap<String, (usize, usize)> =
        std::collections::HashMap::new();
    for event in &result.events {
        let Some(entity) = event.fields.get("src_ip").and_then(|v| v.as_str()) else {
            continue;
        };
        let Some(success) = event.fields.get("success").and_then(|v| v.as_bool()) else {
            continue;
        };
        let entry = counts_by_entity.entry(entity.to_string()).or_default();
        if success {
            entry.1 += 1;
        } else {
            entry.0 += 1;
        }
    }

    assert!(
        counts_by_entity
            .values()
            .any(|(scan_count, login_count)| *scan_count >= 5 && *login_count >= 3),
        "expected one injected entity with 5 scan and 3 login events, got {counts_by_entity:?}"
    );

    let start = "2024-01-01T00:00:00Z".parse().unwrap();
    let duration = Duration::from_secs(600);
    let oracle = run_oracle(&result.events, &plans, &start, &duration, None).unwrap();
    assert!(
        !oracle.alerts.is_empty(),
        "multi-step bind-filter hit should trigger oracle"
    );
}

#[test]
fn test_syntax_seq_entity_is_preserved_as_cluster_field() {
    let input = r#"
#[duration=5s]
scenario inject_entity<seed=42> {
    traffic {
        stream LoginWindow gen 20/s
    }
    injection {
        hit<50%> LoginWindow {
            username seq {
                use(success=false) with(5)
            }
        }
    }
    expect {
        hit(brute_force) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    assert!(wfg.scenario.injects.is_empty());

    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan()];
    let result = generate(&wfg, &schemas, &plans).unwrap();

    let entity_values: Vec<_> = result
        .events
        .iter()
        .filter_map(|event| event.fields.get("username").and_then(|v| v.as_str()))
        .filter(|username| username.starts_with("hit_username_"))
        .collect();

    assert!(
        entity_values.len() >= 50,
        "expected syntax seq entity field to be generated on inject events"
    );
}

#[test]
fn test_syntax_injection_case_targets_multiple_rules() {
    let input = r#"
#[duration=5s]
scenario inject_targets<seed=42> {
    traffic {
        stream LoginWindow gen 40/s
    }
    injection {
        hit<25%> for brute_force LoginWindow {
            src_ip seq {
                use(success=false) with(5)
            }
        }
        hit<25%> for bool_chain LoginWindow {
            username seq {
                use(success=false) with(1)
                then use(success=true) with(1)
            }
        }
    }
    expect {
        hit(brute_force) >= 0%
        hit(bool_chain) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan(), make_bool_chain_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();

    let ip_targeted = result.events.iter().any(|event| {
        event
            .fields
            .get("src_ip")
            .and_then(|v| v.as_str())
            .is_some_and(|src_ip| src_ip.starts_with("10."))
    });
    let user_targeted = result.events.iter().any(|event| {
        event
            .fields
            .get("username")
            .and_then(|v| v.as_str())
            .is_some_and(|username| username.starts_with("hit_username_"))
    });

    assert!(ip_targeted, "expected brute_force-targeted inject events");
    assert!(user_targeted, "expected bool_chain-targeted inject events");
}

#[test]
fn test_syntax_injection_multi_rule_expect_without_target_fails_generation() {
    let input = r#"
#[duration=5s]
scenario inject_targets<seed=42> {
    traffic {
        stream LoginWindow gen 40/s
    }
    injection {
        hit<25%> LoginWindow {
            src_ip seq {
                use(success=false) with(5)
            }
        }
    }
    expect {
        hit(brute_force) >= 0%
        hit(bool_chain) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan()];

    let err = match generate(&wfg, &schemas, &plans) {
        Ok(_) => panic!("generation should fail without explicit target rule"),
        Err(err) => err,
    };
    let rendered = err.report().render().to_string();
    assert!(
        rendered.contains("requires 'for RULE'"),
        "unexpected error: {rendered}"
    );
}

#[test]
fn test_inject_near_miss_no_trigger() {
    // near-miss events should produce N-1 events per cluster (not enough to trigger)
    let input = r#"
#[duration=10s]
scenario inject_nm<seed=42> {
    traffic {
        stream LoginWindow gen 100/s
    }
    injection {
        near_miss<40%> LoginWindow {
            src_ip seq {
                use(action="failed") with(5)
            }
        }
    }
    expect {
        hit(brute_force) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    assert_eq!(result.events.len(), 1000);

    // Run oracle — near-miss clusters should NOT produce alerts
    let start = "2024-01-01T00:00:00Z".parse().unwrap();
    let duration = Duration::from_secs(3600);
    let oracle = run_oracle(&result.events, &plans, &start, &duration, None).unwrap();
    assert_eq!(
        oracle.alerts.len(),
        0,
        "near-miss clusters should not trigger any alerts"
    );
}

#[test]
fn test_syntax_near_miss_uses_explicit_use_step_count() {
    let input = r#"
#[duration=10s]
scenario inject_nm_syntax<seed=42> {
    traffic {
        stream LoginWindow gen 100/s
    }
    injection {
        near_miss<20%> LoginWindow {
            username seq {
                use(success=false) with(2)
            }
        }
    }
    expect {
        hit(brute_force) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    assert_eq!(result.events.len(), 1000);

    let mut by_entity: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    for event in &result.events {
        let Some(username) = event.fields.get("username").and_then(|v| v.as_str()) else {
            continue;
        };
        if !username.starts_with("nm_username_") {
            continue;
        }
        assert_eq!(
            event.fields.get("success").and_then(|v| v.as_bool()),
            Some(false),
            "near_miss use(...) predicates should be applied to generated events"
        );
        *by_entity.entry(username.to_string()).or_default() += 1;
    }

    assert!(
        !by_entity.is_empty(),
        "expected near_miss inject entities with generated username prefix"
    );
    assert!(
        by_entity.values().all(|count| *count == 2),
        "near_miss syntax should honor with(2) instead of rule threshold - 1, got {by_entity:?}"
    );

    let start = "2024-01-01T00:00:00Z".parse().unwrap();
    let duration = Duration::from_secs(3600);
    let oracle = run_oracle(&result.events, &plans, &start, &duration, None).unwrap();
    assert_eq!(
        oracle.alerts.len(),
        0,
        "near_miss clusters with 2 events must not trigger threshold 5 rule"
    );
}

#[test]
fn test_syntax_miss_uses_explicit_use_step_count_and_predicates() {
    let input = r#"
#[duration=10s]
scenario inject_miss_syntax<seed=42> {
    traffic {
        stream LoginWindow gen 100/s
    }
    injection {
        miss<20%> LoginWindow {
            username seq {
                use(success=true) with(5)
            }
        }
    }
    expect {
        hit(brute_force) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    assert_eq!(result.events.len(), 1000);

    let mut by_entity: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    for event in &result.events {
        let Some(username) = event.fields.get("username").and_then(|v| v.as_str()) else {
            continue;
        };
        if !username.starts_with("miss_username_") {
            continue;
        }
        assert_eq!(
            event.fields.get("success").and_then(|v| v.as_bool()),
            Some(true),
            "miss use(...) predicates should be applied to generated events"
        );
        *by_entity.entry(username.to_string()).or_default() += 1;
    }

    assert!(
        !by_entity.is_empty(),
        "expected miss inject entities with generated username prefix"
    );
    assert!(
        by_entity.values().all(|count| *count == 1),
        "miss syntax should give each generated event a unique entity, got {by_entity:?}"
    );

    let start = "2024-01-01T00:00:00Z".parse().unwrap();
    let duration = Duration::from_secs(3600);
    let oracle = run_oracle(&result.events, &plans, &start, &duration, None).unwrap();
    assert_eq!(
        oracle.alerts.len(),
        0,
        "miss events should use unique entities and must not trigger alerts even when with(5)"
    );
}

#[test]
fn test_syntax_miss_allows_predicates_to_override_rule_filter() {
    let input = r#"
#[duration=10s]
scenario inject_miss_filter_override<seed=42> {
    traffic {
        stream LoginWindow gen 100/s
    }
    injection {
        miss<20%> LoginWindow {
            username seq {
                use(success=true) with(5)
            }
        }
    }
    expect {
        hit(auth_fail_rule) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_auth_fail_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    assert_eq!(result.events.len(), 1000);

    let miss_events: Vec<_> = result
        .events
        .iter()
        .filter(|event| {
            event
                .fields
                .get("username")
                .and_then(|v| v.as_str())
                .is_some_and(|username| username.starts_with("miss_username_"))
        })
        .collect();

    assert!(
        !miss_events.is_empty(),
        "expected miss inject events with generated username prefix"
    );
    assert!(
        miss_events
            .iter()
            .all(|event| event.fields.get("success").and_then(|v| v.as_bool()) == Some(true)),
        "miss predicates should override auth_fail_rule success=false filter"
    );

    let start = "2024-01-01T00:00:00Z".parse().unwrap();
    let duration = Duration::from_secs(3600);
    let oracle = run_oracle(&result.events, &plans, &start, &duration, None).unwrap();
    assert_eq!(
        oracle.alerts.len(),
        0,
        "miss filter overrides should not trigger auth_fail_rule alerts"
    );
}

#[test]
fn test_inject_hit_triggers_oracle() {
    let input = r#"
#[duration=10s]
scenario inject_oracle<seed=42> {
    traffic {
        stream LoginWindow gen 100/s
    }
    injection {
        hit<50%> LoginWindow {
            src_ip seq {
                use(action="failed") with(5)
            }
        }
    }
    expect {
        hit(brute_force) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();

    // Run oracle — hit clusters should produce alerts
    let start = "2024-01-01T00:00:00Z".parse().unwrap();
    let duration = Duration::from_secs(3600);
    let oracle = run_oracle(&result.events, &plans, &start, &duration, None).unwrap();

    // 1000 events * 50% = 500 hit events / 5 per cluster = 100 clusters → 100 alerts
    assert_eq!(
        oracle.alerts.len(),
        100,
        "expected 100 alerts from 100 hit clusters, got {}",
        oracle.alerts.len()
    );

    // All alerts should have correct rule name and score
    for alert in &oracle.alerts {
        assert_eq!(alert.rule_name, "brute_force");
        assert!((alert.score - 85.0).abs() < f64::EPSILON);
        assert_eq!(alert.entity_type, "ip");
    }
}

#[test]
fn test_inject_budget_allocation() {
    // hit% + near_miss% + non_hit% should be accounted for; rest is background
    let input = r#"
#[duration=10s]
scenario inject_budget<seed=42> {
    traffic {
        stream LoginWindow gen 100/s
    }
    injection {
        hit<30%> LoginWindow {
            src_ip seq {
                use(action="failed") with(5)
            }
        }
        near_miss<10%> LoginWindow {
            src_ip seq {
                use(action="failed") with(5)
            }
        }
        miss<20%> LoginWindow {
            src_ip seq {
                use(action="success") with(1)
            }
        }
    }
    expect {
        hit(brute_force) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    // Total should still be 1000
    assert_eq!(result.events.len(), 1000);
}

#[test]
fn test_inject_deterministic() {
    let input = r#"
#[duration=5s]
scenario inject_det<seed=42> {
    traffic {
        stream LoginWindow gen 100/s
    }
    injection {
        hit<30%> LoginWindow {
            src_ip seq {
                use(action="failed") with(5)
            }
        }
    }
    expect {
        hit(brute_force) >= 0%
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan()];

    let result1 = generate(&wfg, &schemas, &plans).unwrap();
    let result2 = generate(&wfg, &schemas, &plans).unwrap();

    assert_eq!(result1.events.len(), result2.events.len());
    for (e1, e2) in result1.events.iter().zip(result2.events.iter()) {
        assert_eq!(e1.timestamp, e2.timestamp);
        assert_eq!(e1.fields, e2.fields);
    }
}
